version: "2"
exclude_patterns:
  - "**/src/main/java/chapi/ast/antlr/"
  - "**/resources/**"
  - "tests/"

plugins:
  duplication:
    enabled: true
    config:
      languages:
        kotlin:
          patterns:
            - "**/*Analyser.kt"
            - "**/*Test.kt"
